### ISSUE TITLE
parser_test fails to run (SIGABRT) on Mac OS X 10.10/clang for most input files

### ISSUE THREAD

**Issue by tstordyallison** [vinzenz/libpypa#11] opened 2014-11-30 15:19 UTC
`AstName` is not being initialised with default values for `AstName.dotted` or `AstName.context`. 

The symbol table code uses dotted to make decisions about module level imports and subsequently fails when the value of dotted is incorrect.

Simple fix to set default values in `ast.hh` (but this does somewhat relax what looks like strict PODs):

```
PYPA_AST_EXPR(Name) {
    AstContext  context = AstContext::Load;
    bool        dotted  = false;
    String      id;
};
```

All of my cpython 2.7 source parses fine under run_tests.sh with this change.

Alternative is to ensure that all usages of `AstName` are initialised correctly, but there are quite a few in `parser.cc`!

 Let me know which way you would prefer to go and I'll fix up and send over a PR.

Tom

**Comment by vinzenz** [comment] 2017-03-29 07:10
Can't reproduce any more now, closing this BZ

**Closed by vinzenz** 2017-03-29 07:10 UTC
